#! /bin/sh

name="km_proga.pas"

while [ -n "$1" ]
do
    case $1 in
        "-h"|"--help")
            echo -e "building pascal program
Usage build.sh [--help] [--create] [--free] [--dotnet] [--elf] [--exe] [--clean]

--help \t \t output this text
--create \t \t create 2 text files with random values
--free \t \t compile main program with Free Pascal
--dotnet \t \t compile program with PascalABC.Net
--elf \t \t start linux program
--exe \t \t start windows program
--clean \t \t cleaning programs and other stuff
"
        ;;

        "--create")
        echo -ne > a.txt
        echo -ne > b.txt
        for file in "a.txt" "b.txt"
        do
            for i in $(seq 1 100)
            do
                for j in $(seq 1 100)
                do
                    if [ $((1 + RANDOM % 3)) -eq 3 ]
                    then
                        echo -ne "-$((1 + RANDOM % 100)) " >> $file
                    else echo -ne "$((1 + RANDOM % 100)) " >> $file
                    fi
                done
                echo >> $file
            done
        done
        echo "Файлы созданы"

        ;;

        "--free")
            cd src/
            fpc $name -oprogram && mv program ../
            cd ..
        ;;

        "--dotnet")
            cd src/
            pabcnetc win_km_proga.pas && mv win_km_proga.exe ../
            cd ../
        ;;

        "--elf")
            echo -ne "\n\nLinux...\n\n"
            ./program a.txt b.txt out.txt
            echo -ne "\n\n..end\n\n"

        ;;

        "--exe")
            echo -ne "\n\nWindows...\n\n"
            LC_ALL=ru_RU.UTF-8 wineconsole win_km_proga.exe a.txt b.txt out.txt
            echo -ne "\n\n...end\n\n"
        ;;

        "--show")
            echo -ne "\n\nСодержимое файла out.txt:\n\n"
            cat out.txt
            echo -ne "\n\n"
        ;;

        "--clean")
            rm -fv *.exe program *.txt src/*.mdb src/*.o
        ;;

    esac
shift
done
